version: "3.9"

volumes:
  frontend-build:

services:
  # ==========================
  # Angular SSR (Frontend)
  # ==========================
  frontend-ssr:
    build:
      context: ./frontend
      dockerfile: Dockerfile.ssr
    container_name: cards-frontend-ssr
    restart: always
    expose:
      - "4000"
    volumes:
      - frontend-build:/app/dist/frontend

  # ==========================
  # Backend (Node.js)
  # ==========================
  backend:
    build: ./backend
    container_name: cards-backend
    restart: always
    expose:
      - "3000"
    ports:
      - "3000:3000"